### ISSUE TITLE
Energy Exports switch is missing

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hacs-teslemetry#19]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/fd87eee9-2df8-4ff1-a834-cc9de7f55a47)

**Comment by Bre77** [comment]
Should be fixed in a future release as I had the key for this value incorrect.
