### ISSUE TITLE
charge_cable state is inverted

### ISSUE THREAD

**Issue by janchrillesen** [Teslemetry/hacs-teslemetry#25]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The binary_sensor charge_cable shows "on"/connected, when no cable is connected

The API returns "conn_charge_cable": "\<invalid\>" when no cable is connected and "conn_charge_cable": "IEC" when a cable is connected (most likely it will return "SAE" in other regions)

In binary_sensor.py "\<invalid\>" is assumed to be on, and everything else is off. This behavior needs to be inverted. Optionally the plug type could be added as an attribute. 

(https://github.com/Teslemetry/hacs-teslemetry/issues/21 might be related - it would be interesting to see what is returned by the API for this specific car)

### Reproduction steps

1. Check the value of binary_sensor.carname_charge_cable 
2. Plug or unplug the charging cable
3. Observe that the sensor is when no cable is connected
...

**Comment by Bre77** [comment]
Yes, yes it is, fix implemented.
