### ISSUE TITLE
Time to Arrival and Distance to Arrival incorrect when not navigating

### ISSUE THREAD

**Issue by JumiranK** [Teslemetry/hacs-teslemetry#26]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When arriving on the destination. The sensor "Time to arrival" is always currentDateTime. What I see with Postman is that the json entity drive_state.active_route_minutes_to_arrival does not exist.

Dived a bit deeper in the issue and I observed that when you cancel navigation. The entries 
- active_route_miles_to_arrival
- active_route_minutes_to_arrival
are dissapearing. So I would expect that the 2 sensors Time To Arrival and Distance To Arrial become both unavailable in HA.

Using release 1.4.6

### Reproduction steps

1. Navigate to an address
2. Once arrived observe that with each sensor update the time of arrival changes with the currentDateTime

**Comment by Bre77** [comment]
This should be fixed in https://github.com/Teslemetry/hacs-teslemetry/releases/tag/v1.5.0
